### ISSUE TITLE
Pipfile.lock is missing

### ISSUE THREAD

**Issue by otariidae** [Azuki-bar/discord-vc-notify#8]
It is recommended to commit `Pipfile.lock` to get deterministic dependencies.

> Generally, keep both Pipfile and Pipfile.lock in version control.

https://pipenv.pypa.io/en/latest/basics/#general-recommendations-version-control

**Comment by Azuki-bar** [comment]
I have thought tracking `pipfile.lock` is redundant. But, the official recommend to track that file.
so I added `pipfile.lock` on #9 .
